### ISSUE TITLE
[São Luís] - Estágio de Desenvolvimento - Universidade CEUMA

### ISSUE THREAD

**Issue by MichelCordeiro** [ditceuma/vagas#6]
## Descrição da vaga

Buscamos pessoas interessadas e comprometidas, que tenham vontade de aprender e que gostem de desafios. Durante o convívio conosco em seu estágio, você vivenciará problemas reais de desenvolvimento e engenharia de software. Assim como desafios de equipes e formas de organização de trabalho.
O foco técnico do estágio é o desenvolvimento de habilidades aplicadas a testes e qualidade de software.

Este estágio é curricular e específico para alunos da Universidade CEUMA.

## Local

Universidade CEUMA – São Luís, MA

## Nossa empresa

Somos a maior Univerisidade do Maranhão e fazemos parte de um grupo educacional com representatividade em 5 estados.

## Como se candidatar

O candidato interessado deverá preencher o formulário do link abaixo:
http://bit.ly/2tlPWJE

O recebimento de currículo estará aberto enquanto essa issue estiver.

**Comment by siandreia21** [comment]
WOW

**Comment by efremfilho** [comment]
Link do form tá quebrado

**Comment by MichelCordeiro** [comment]
Opa, valeu. O link já está ok.
