### ISSUE TITLE
[São Luís] - Desenvolvedor - Universidade CEUMA

### ISSUE THREAD

**Issue by araoalves** [ditceuma/vagas#9]
## Descrição da vaga

Buscamos desenvolvedores para criar novos produtos e dar suporte em produtos já existentes. 
O desenvolvedor deverá somar para disseminação da cultura ágil trazendo experiência com as abordagens. Terá liberdade de propor ideias, modelos e liderar produtos que tenham relevância para o segmento educacional. 

## Local

Universidade CEUMA – São Luís, MA, Renascença

## Benefícios

- Vale transporte;
- Plano hospitalar;
- Estacionamento gratuito;
- Praça de Alimentação dentro da própria Universidade;

## Requisitos

**Obrigatórios:**
- Ter conhecimentos em TDD e desenvolver orientado a testes;
- Bons conhecimentos em Java,  Bootstrap, Angular;
- Ser fera em desenvolvimento de APIs;
- Ter experiência com frameworks Java EE (maven, spring-boot, vraptor, jsf, hibernate, etc); 
- Ter conhecimento de XP;
- Fazendo curso superior, preferencialmente períodos finais ou já formado;

**Desejáveis:**
- Conhecimento em C#;
- Conhecimento em ASP.Net e VB6;
- Experiência com Scrum ou método Kanban;

**Diferenciais:**
- Conhecimentos em desenvolvimento Android;
- Conhecimento em desenvolvimento iOS;
- Conhecimentos em Ionic;
- Conhecimentos em React;
- Conhecimentos em Golang;
- Conhecimento com Jenkins, Sonarqube, Vagrant, Docker, Puppet ou outras ferramentas de DevOps;
- Projetos OpenSource contam pontos;
- Ter sido palestrante em eventos;
- Conhecimento de linguagens funcionais;
- Certificação SCRUM;
- Certificação Java;

## Contratação

CLT

## Nossa empresa

Somos a maior e melhor Universidade Particular do Norte, Nordeste e Centro-Oeste, e fazemos parte de um grupo educacional com representatividade em 5 estados.

## Como se candidatar

A vaga está aberta a profissionais de todo o país. O candidato interessado deverá mandar um e-mail para vagas-devti@grupoceuma.com.br com o seu CV, endereço do LinkedIn e GitHub, se tiver (sendo um diferencial). Deve enviar no assunto: Vaga Desenvolvedor – CEUMA, com seu nome no CV no formato pdf.
O recebimento de currículo estará aberto enquanto essa issue estiver.

**Comment by atmosmaciel** [comment]
@araoalves o que você acha de nós movermos essas informações para o README do projeto? Não é mais coerente? Podemos adicionar as Labels e tornar a vaga mais exposta para o participantes. As Issues podem ficar como espaço para candidatos tirarem suas dúvidas ou relatarem problemas... etc.
